-- Migration 108: Concierge ticketing — core ticket-scoped tables.
--
-- Depends on 106 (enums + clients/profiles.concierge_group) and 107 (lookup tables).
-- Creates, in FK-dependency order:
--   concierge_tickets
--   concierge_ticket_updates          (append-only timeline — NO update/delete policy)
--   concierge_ticket_attachments
--   concierge_ticket_checklist_items
--   ticket_invoices
--   vendor_feedback
--   concierge_ticket_notifications
--
-- NOTE on the org-half column: it is named `org_group` (NOT `group`) — `group` is a
-- reserved SQL keyword that would require double-quoting everywhere. Same enum,
-- same meaning; the UI labels it "Group".
--
-- Access model (build spec §6), enforced by two SECURITY DEFINER helpers so the
-- child-table policies stay DRY and non-recursive:
--   * view  = admin/founder/super_admin | finance | (concierge AND group matches)
--   * edit  = admin/founder/super_admin | (concierge AND group matches AND
--             (assigned genie OR manager))

-- ── concierge_tickets ────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.concierge_tickets (
  id                     uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  ref_number             bigint      GENERATED BY DEFAULT AS IDENTITY (START WITH 20000) UNIQUE,
  client_id              uuid        NOT NULL REFERENCES public.clients(id) ON DELETE RESTRICT,

  title                  text        NOT NULL,   -- sanitized before write
  description            text        NULL,       -- sanitized before write

  category_id            uuid        NOT NULL REFERENCES public.ticket_categories(id),
  subcategory_id         uuid        NULL REFERENCES public.ticket_categories(id),

  org_group              public.concierge_group        NOT NULL,
  status                 public.concierge_ticket_status NOT NULL DEFAULT 'open',
  priority               public.concierge_ticket_priority NOT NULL DEFAULT 'medium',

  assigned_to            uuid        NULL REFERENCES public.profiles(id) ON DELETE SET NULL,
  created_by             uuid        NOT NULL REFERENCES public.profiles(id) ON DELETE RESTRICT,

  is_billable            boolean     NULL,        -- NULL = decision not yet made
  invoice_number         text        NULL,
  primary_vendor_id      uuid        NULL REFERENCES public.vendors(id) ON DELETE SET NULL,

  -- SLA + lifecycle timestamps (tz-aware; IST business clock computed in app layer)
  status_changed_at      timestamptz NOT NULL DEFAULT now(),
  first_response_at      timestamptz NULL,
  sla_first_response_due timestamptz NULL,
  sla_resolution_due     timestamptz NULL,
  is_overdue             boolean     NOT NULL DEFAULT false,
  resolved_at            timestamptz NULL,
  closed_at              timestamptz NULL,

  created_at             timestamptz NOT NULL DEFAULT now(),
  updated_at             timestamptz NOT NULL DEFAULT now(),

  -- subcategory, when present, must be a child of category
  CONSTRAINT concierge_tickets_subcategory_differs CHECK (subcategory_id IS NULL OR subcategory_id <> category_id)
);

CREATE INDEX IF NOT EXISTS idx_concierge_tickets_assigned_to ON public.concierge_tickets (assigned_to);
CREATE INDEX IF NOT EXISTS idx_concierge_tickets_group_status ON public.concierge_tickets (org_group, status);
CREATE INDEX IF NOT EXISTS idx_concierge_tickets_status_changed ON public.concierge_tickets (status, status_changed_at);
CREATE INDEX IF NOT EXISTS idx_concierge_tickets_client ON public.concierge_tickets (client_id);
CREATE INDEX IF NOT EXISTS idx_concierge_tickets_created ON public.concierge_tickets (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_concierge_tickets_overdue ON public.concierge_tickets (org_group) WHERE is_overdue;

CREATE TRIGGER concierge_tickets_updated_at
  BEFORE UPDATE ON public.concierge_tickets
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ── Visibility helpers (SECURITY DEFINER — bypass ticket RLS to avoid recursion) ─

CREATE OR REPLACE FUNCTION public.can_view_concierge_ticket(p_ticket_id uuid)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.concierge_tickets t
    WHERE t.id = p_ticket_id
      AND (
        public.get_user_role() IN ('admin', 'founder', 'super_admin')
        OR public.get_user_department() = 'finance'
        OR (
          public.get_user_department() = 'concierge'
          AND t.org_group::text = (SELECT p.concierge_group::text FROM public.profiles p WHERE p.id = auth.uid())
        )
      )
  );
$$;

CREATE OR REPLACE FUNCTION public.can_edit_concierge_ticket(p_ticket_id uuid)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.concierge_tickets t
    WHERE t.id = p_ticket_id
      AND (
        public.get_user_role() IN ('admin', 'founder', 'super_admin')
        OR (
          public.get_user_department() = 'concierge'
          AND t.org_group::text = (SELECT p.concierge_group::text FROM public.profiles p WHERE p.id = auth.uid())
          AND (t.assigned_to = auth.uid() OR public.get_user_role() = 'manager')
        )
      )
  );
$$;

-- ── concierge_tickets RLS ────────────────────────────────────────────────────

ALTER TABLE public.concierge_tickets ENABLE ROW LEVEL SECURITY;

CREATE POLICY "concierge_tickets_select"
  ON public.concierge_tickets FOR SELECT TO authenticated
  USING (
    public.get_user_role() IN ('admin', 'founder', 'super_admin')
    OR public.get_user_department() = 'finance'
    OR (
      public.get_user_department() = 'concierge'
      AND org_group::text = (SELECT p.concierge_group::text FROM public.profiles p WHERE p.id = auth.uid())
    )
  );

-- INSERT: bishops (manager+concierge, own group) and privileged roles.
CREATE POLICY "concierge_tickets_insert"
  ON public.concierge_tickets FOR INSERT TO authenticated
  WITH CHECK (
    public.get_user_role() IN ('admin', 'founder', 'super_admin')
    OR (
      public.get_user_role() = 'manager'
      AND public.get_user_department() = 'concierge'
      AND org_group::text = (SELECT p.concierge_group::text FROM public.profiles p WHERE p.id = auth.uid())
    )
  );

-- UPDATE: privileged anywhere; assigned genie or any concierge manager in-group.
CREATE POLICY "concierge_tickets_update"
  ON public.concierge_tickets FOR UPDATE TO authenticated
  USING (
    public.get_user_role() IN ('admin', 'founder', 'super_admin')
    OR (
      public.get_user_department() = 'concierge'
      AND org_group::text = (SELECT p.concierge_group::text FROM public.profiles p WHERE p.id = auth.uid())
      AND (assigned_to = auth.uid() OR public.get_user_role() = 'manager')
    )
  )
  WITH CHECK (
    public.get_user_role() IN ('admin', 'founder', 'super_admin')
    OR (
      public.get_user_department() = 'concierge'
      AND org_group::text = (SELECT p.concierge_group::text FROM public.profiles p WHERE p.id = auth.uid())
      AND (assigned_to = auth.uid() OR public.get_user_role() = 'manager')
    )
  );

CREATE POLICY "concierge_tickets_service_role"
  ON public.concierge_tickets
  USING (auth.role() = 'service_role');

-- ── concierge_ticket_updates (append-only timeline) ──────────────────────────

CREATE TABLE IF NOT EXISTS public.concierge_ticket_updates (
  id         uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  ticket_id  uuid        NOT NULL REFERENCES public.concierge_tickets(id) ON DELETE CASCADE,
  author_id  uuid        NULL REFERENCES public.profiles(id) ON DELETE SET NULL,   -- NULL = pure system entry
  kind       public.concierge_update_kind NOT NULL,
  body       text        NULL,                        -- sanitized; notes / canned responses
  metadata   jsonb       NOT NULL DEFAULT '{}',       -- {old_status,new_status} | {old_assignee,new_assignee} | {template_id} | {tracking_id} ...
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_concierge_ticket_updates_ticket
  ON public.concierge_ticket_updates (ticket_id, created_at DESC);

ALTER TABLE public.concierge_ticket_updates ENABLE ROW LEVEL SECURITY;

-- Append-only: SELECT + INSERT only. NO update / delete policy, ever.
CREATE POLICY "concierge_ticket_updates_select"
  ON public.concierge_ticket_updates FOR SELECT TO authenticated
  USING (public.can_view_concierge_ticket(ticket_id));

CREATE POLICY "concierge_ticket_updates_insert"
  ON public.concierge_ticket_updates FOR INSERT TO authenticated
  WITH CHECK (public.can_edit_concierge_ticket(ticket_id));

CREATE POLICY "concierge_ticket_updates_service_role"
  ON public.concierge_ticket_updates
  USING (auth.role() = 'service_role');

-- ── concierge_ticket_attachments ─────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.concierge_ticket_attachments (
  id           uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  ticket_id    uuid        NOT NULL REFERENCES public.concierge_tickets(id) ON DELETE CASCADE,
  update_id    uuid        NULL REFERENCES public.concierge_ticket_updates(id) ON DELETE SET NULL,
  uploaded_by  uuid        NULL REFERENCES public.profiles(id) ON DELETE SET NULL,
  storage_path text        NOT NULL,                  -- concierge/{ticket_id}/{uuid}-{filename}
  file_name    text        NOT NULL,
  mime_type    text        NOT NULL,
  size_bytes   bigint      NOT NULL CHECK (size_bytes >= 0),
  kind         text        NOT NULL CHECK (kind IN ('image', 'pdf', 'video', 'other')),
  is_proof     boolean     NOT NULL DEFAULT false,    -- proof-of-confirmation for Ongoing Delivery
  created_at   timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_concierge_ticket_attachments_ticket
  ON public.concierge_ticket_attachments (ticket_id);
CREATE INDEX IF NOT EXISTS idx_concierge_ticket_attachments_proof
  ON public.concierge_ticket_attachments (ticket_id) WHERE is_proof;

ALTER TABLE public.concierge_ticket_attachments ENABLE ROW LEVEL SECURITY;

CREATE POLICY "concierge_ticket_attachments_select"
  ON public.concierge_ticket_attachments FOR SELECT TO authenticated
  USING (public.can_view_concierge_ticket(ticket_id));

CREATE POLICY "concierge_ticket_attachments_insert"
  ON public.concierge_ticket_attachments FOR INSERT TO authenticated
  WITH CHECK (public.can_edit_concierge_ticket(ticket_id));

CREATE POLICY "concierge_ticket_attachments_update"
  ON public.concierge_ticket_attachments FOR UPDATE TO authenticated
  USING (public.can_edit_concierge_ticket(ticket_id))
  WITH CHECK (public.can_edit_concierge_ticket(ticket_id));

CREATE POLICY "concierge_ticket_attachments_service_role"
  ON public.concierge_ticket_attachments
  USING (auth.role() = 'service_role');

-- ── concierge_ticket_checklist_items (snapshotted from templates at creation) ─

CREATE TABLE IF NOT EXISTS public.concierge_ticket_checklist_items (
  id          uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  ticket_id   uuid        NOT NULL REFERENCES public.concierge_tickets(id) ON DELETE CASCADE,
  template_id uuid        NULL REFERENCES public.ticket_checklist_templates(id) ON DELETE SET NULL,
  label       text        NOT NULL,                   -- snapshotted
  sort_order  integer     NOT NULL DEFAULT 0,
  is_checked  boolean     NOT NULL DEFAULT false,
  checked_by  uuid        NULL REFERENCES public.profiles(id) ON DELETE SET NULL,
  checked_at  timestamptz NULL
);

CREATE INDEX IF NOT EXISTS idx_concierge_ticket_checklist_items_ticket
  ON public.concierge_ticket_checklist_items (ticket_id, sort_order);

ALTER TABLE public.concierge_ticket_checklist_items ENABLE ROW LEVEL SECURITY;

CREATE POLICY "concierge_ticket_checklist_items_select"
  ON public.concierge_ticket_checklist_items FOR SELECT TO authenticated
  USING (public.can_view_concierge_ticket(ticket_id));

CREATE POLICY "concierge_ticket_checklist_items_insert"
  ON public.concierge_ticket_checklist_items FOR INSERT TO authenticated
  WITH CHECK (public.can_edit_concierge_ticket(ticket_id));

CREATE POLICY "concierge_ticket_checklist_items_update"
  ON public.concierge_ticket_checklist_items FOR UPDATE TO authenticated
  USING (public.can_edit_concierge_ticket(ticket_id))
  WITH CHECK (public.can_edit_concierge_ticket(ticket_id));

CREATE POLICY "concierge_ticket_checklist_items_service_role"
  ON public.concierge_ticket_checklist_items
  USING (auth.role() = 'service_role');

-- ── ticket_invoices (Invoice Due payload → Finance) ──────────────────────────

CREATE TABLE IF NOT EXISTS public.ticket_invoices (
  id                 uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  ticket_id          uuid        NOT NULL UNIQUE REFERENCES public.concierge_tickets(id) ON DELETE CASCADE,
  client_name        text        NOT NULL,
  description        text        NOT NULL,
  cost_price         numeric     NOT NULL CHECK (cost_price >= 0),
  selling_price      numeric     NOT NULL CHECK (selling_price >= 0),
  service_charge     numeric     NOT NULL CHECK (service_charge >= 0),
  vendor_id          uuid        NULL REFERENCES public.vendors(id) ON DELETE SET NULL,
  vendor_name        text        NULL,
  vendor_bill_att_id uuid        NULL REFERENCES public.concierge_ticket_attachments(id) ON DELETE SET NULL,
  payment_method     text        NOT NULL,           -- 'razorpay' | 'card' | 'upi' | ...
  invoice_att_id     uuid        NULL REFERENCES public.concierge_ticket_attachments(id) ON DELETE SET NULL,
  bill_in_other_name text        NULL,
  created_by         uuid        NULL REFERENCES public.profiles(id) ON DELETE SET NULL,
  created_at         timestamptz NOT NULL DEFAULT now(),
  updated_at         timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_ticket_invoices_ticket ON public.ticket_invoices (ticket_id);

CREATE TRIGGER ticket_invoices_updated_at
  BEFORE UPDATE ON public.ticket_invoices
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

ALTER TABLE public.ticket_invoices ENABLE ROW LEVEL SECURITY;

-- Finance + privileged + the concierge editor of the ticket may read/write invoices.
CREATE POLICY "ticket_invoices_select"
  ON public.ticket_invoices FOR SELECT TO authenticated
  USING (
    public.get_user_role() IN ('admin', 'founder', 'super_admin')
    OR public.get_user_department() = 'finance'
    OR public.can_view_concierge_ticket(ticket_id)
  );

CREATE POLICY "ticket_invoices_insert"
  ON public.ticket_invoices FOR INSERT TO authenticated
  WITH CHECK (
    public.get_user_role() IN ('admin', 'founder', 'super_admin')
    OR public.get_user_department() = 'finance'
    OR public.can_edit_concierge_ticket(ticket_id)
  );

CREATE POLICY "ticket_invoices_update"
  ON public.ticket_invoices FOR UPDATE TO authenticated
  USING (
    public.get_user_role() IN ('admin', 'founder', 'super_admin')
    OR public.get_user_department() = 'finance'
    OR public.can_edit_concierge_ticket(ticket_id)
  )
  WITH CHECK (
    public.get_user_role() IN ('admin', 'founder', 'super_admin')
    OR public.get_user_department() = 'finance'
    OR public.can_edit_concierge_ticket(ticket_id)
  );

CREATE POLICY "ticket_invoices_service_role"
  ON public.ticket_invoices
  USING (auth.role() = 'service_role');

-- ── vendor_feedback (captured on resolve) ────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.vendor_feedback (
  id         uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  vendor_id  uuid        NOT NULL REFERENCES public.vendors(id) ON DELETE CASCADE,
  ticket_id  uuid        NOT NULL REFERENCES public.concierge_tickets(id) ON DELETE CASCADE,
  quality    integer     NOT NULL CHECK (quality BETWEEN 1 AND 5),
  promptness public.vendor_promptness NOT NULL,
  cost       public.vendor_cost_band  NOT NULL,
  delivery   public.vendor_delivery   NOT NULL,
  created_by uuid        NULL REFERENCES public.profiles(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_vendor_feedback_vendor ON public.vendor_feedback (vendor_id);
CREATE INDEX IF NOT EXISTS idx_vendor_feedback_ticket ON public.vendor_feedback (ticket_id);

ALTER TABLE public.vendor_feedback ENABLE ROW LEVEL SECURITY;

CREATE POLICY "vendor_feedback_select"
  ON public.vendor_feedback FOR SELECT TO authenticated
  USING (
    public.get_user_role() IN ('admin', 'founder', 'super_admin')
    OR public.get_user_department() IN ('concierge', 'finance')
  );

CREATE POLICY "vendor_feedback_insert"
  ON public.vendor_feedback FOR INSERT TO authenticated
  WITH CHECK (public.can_edit_concierge_ticket(ticket_id));

CREATE POLICY "vendor_feedback_service_role"
  ON public.vendor_feedback
  USING (auth.role() = 'service_role');

-- ── concierge_ticket_notifications (parallel to task_notifications) ───────────

CREATE TABLE IF NOT EXISTS public.concierge_ticket_notifications (
  id           uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  recipient_id uuid        NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  actor_id     uuid        NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  type         public.concierge_ticket_notification_type NOT NULL,
  ticket_id    uuid        NOT NULL REFERENCES public.concierge_tickets(id) ON DELETE CASCADE,
  title        text        NOT NULL,
  body         text        NULL,
  read_at      timestamptz NULL,
  created_at   timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_concierge_ticket_notifications_recipient_created
  ON public.concierge_ticket_notifications (recipient_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_concierge_ticket_notifications_unread
  ON public.concierge_ticket_notifications (recipient_id) WHERE read_at IS NULL;

ALTER TABLE public.concierge_ticket_notifications ENABLE ROW LEVEL SECURITY;

-- Own-row read + read_at flip only. Inserts go through the service role.
CREATE POLICY "concierge_ticket_notifications_select"
  ON public.concierge_ticket_notifications FOR SELECT TO authenticated
  USING (recipient_id = auth.uid());

CREATE POLICY "concierge_ticket_notifications_update"
  ON public.concierge_ticket_notifications FOR UPDATE TO authenticated
  USING (recipient_id = auth.uid())
  WITH CHECK (recipient_id = auth.uid());

CREATE POLICY "concierge_ticket_notifications_service_role"
  ON public.concierge_ticket_notifications
  USING (auth.role() = 'service_role');

-- ── Realtime publication (live timeline + notifications + list status) ────────

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables
    WHERE pubname = 'supabase_realtime' AND schemaname = 'public' AND tablename = 'concierge_ticket_updates'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.concierge_ticket_updates;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables
    WHERE pubname = 'supabase_realtime' AND schemaname = 'public' AND tablename = 'concierge_ticket_notifications'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.concierge_ticket_notifications;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables
    WHERE pubname = 'supabase_realtime' AND schemaname = 'public' AND tablename = 'concierge_tickets'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.concierge_tickets;
  END IF;
END $$;
